/****** Object:  Database DiscordBot    Script Date: 7/30/2021 10:19:13 PM ******/
CREATE DATABASE DiscordBot  (EDITION = 'Basic', SERVICE_OBJECTIVE = 'Basic', MAXSIZE = 2 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO

ALTER DATABASE DiscordBot SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE DiscordBot SET ANSI_NULLS OFF 
GO

ALTER DATABASE DiscordBot SET ANSI_PADDING OFF 
GO

ALTER DATABASE DiscordBot SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE DiscordBot SET ARITHABORT OFF 
GO

ALTER DATABASE DiscordBot SET AUTO_SHRINK OFF 
GO

ALTER DATABASE DiscordBot SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE DiscordBot SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE DiscordBot SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE DiscordBot SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE DiscordBot SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE DiscordBot SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE DiscordBot SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE DiscordBot SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE DiscordBot SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE DiscordBot SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE DiscordBot SET  MULTI_USER 
GO

ALTER DATABASE DiscordBot SET ENCRYPTION ON
GO

ALTER DATABASE DiscordBot SET QUERY_STORE = ON
GO

ALTER DATABASE DiscordBot SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

/*** The scripts of database scoped configurations in Azure should be executed inside the target database connection. ***/
--GO

-- ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 8;
--GO

ALTER DATABASE DiscordBot SET  READ_WRITE 
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.cryptoPrices(
	id int IDENTITY(1,1) NOT NULL,
	coinName varchar(100) NOT NULL,
	price float NOT NULL,
	midPrice float NULL,
	olderPrice float NULL,
	oldestPrice float NULL,
	dateAdded date NOT NULL
) ON PRIMARY
GO

ALTER TABLE dbo.cryptoPrices ADD  CONSTRAINT DF_cryptoPrices_dateAdded  DEFAULT (getdate()) FOR dateAdded
GO

/****** Object:  Table dbo.ServerTable    Script Date: 7/30/2021 10:22:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.ServerTable(
	id int IDENTITY(1,1) NOT NULL,
	server_id bigint NOT NULL,
	server_name varchar(100) NOT NULL,
 CONSTRAINT PK_ServerTable PRIMARY KEY CLUSTERED 
(
	server_id ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
) ON PRIMARY
GO

/****** Object:  Table dbo.UserExperience    Script Date: 7/30/2021 10:22:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.UserExperience(
	id int IDENTITY(1,1) NOT NULL,
	server_id bigint NOT NULL,
	user_id bigint NOT NULL,
	bank float NOT NULL,
	wallet float NOT NULL,
	messages bigint NOT NULL,
	userLevel bigint NOT NULL,
	experience bigint NOT NULL,
	emojiSent bigint NOT NULL,
	reactionsReceived bigint NOT NULL,
	dateAdded datetime NOT NULL,
	dateUpdated datetime NOT NULL,
 CONSTRAINT PK_UserExperience PRIMARY KEY CLUSTERED 
(
	id ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
) ON PRIMARY
GO

ALTER TABLE dbo.UserExperience ADD  CONSTRAINT DF_UserExperience_dateAdded  DEFAULT (getdate()) FOR dateAdded
GO

/****** Object:  Table dbo.Users    Script Date: 7/30/2021 10:23:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.Users(
	id int IDENTITY(1,1) NOT NULL,
	user_id bigint NOT NULL,
	username varchar(100) NOT NULL,
 CONSTRAINT PK_Users_1 PRIMARY KEY CLUSTERED 
(
	user_id ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
) ON PRIMARY
GO




